### ISSUE TITLE
Per-channel filters

### ISSUE THREAD

**Issue by kornelski** [PistonDevelopers/resize#21]
Sharpening filters are good for resizing RGB channels, but they're inappropriate for the alpha channel (since the halos make transparent pixels opaque and create false outlines).

How would you recommend to solve that problem? 

Should there be an API for setting different filters per channel? Should alpha always be hardcoded to use bicubic?

**Comment by kornelski** [comment]
There's a similar edge case if you resize without preserving aspect ratio and you make width wider, and height smaller (or vice versa), then you may want a different filter for each axis.

**Comment by Kagami** [comment]
I think explicit API is better.
Btw, would you like to have push access to the repo? You have more knowledge of the topic than I.

**Comment by kornelski** [comment]
Thanks for your input.

I'm interested in developing the project further, but I'm not sure if my goals match yours. 

For example, I'm not interested in having pixel-perfect match with ImageMagick. I'd like to use fixed-point math to improve the speed, but that would differ from what IM does.

There's also a question how much complexity is right for the project. I'm interested in using linear light for pixel blending and offer an API for resizing in a streaming (unbuffered) iterator.

**Comment by Kagami** [comment]
>having pixel-perfect match with ImageMagick

Actually I don't think it's important either. I added this comparision at the beginning just to be sure I'm doing the right thing. Removed this from readme.

>I'd like to use fixed-point math to improve the speed

That would be nice. Maybe make it optional? [Here](https://www.imagemagick.org/Usage/filter/nicolas/) Nicolas recommends to use tensor scaling only with floating point intermediate buffers, to get high-quality result.

>I'm interested in using linear light for pixel blending and offer an API for resizing in a streaming (unbuffered) iterator

I'm ok with it. My only suggestions are no deps unless it's really needed (because I want this lib to be focused on single task, resizing, so it should be quite small and lightweight to include to any other project) and explicit API because users have different usecases and this lib aims to provide low-level access for resizing. Though we can always discuss this further.

I added you as collaborator, feel free to push new contributions.

**Comment by kornelski** [comment]
I've tested resampling RGB with one filter, and alpha with another. The results were disappointing.

Differences between filters create mismatch between RGB and A channels, which adds halos/distortions on the edges. When enlarging it looks pretty bad even in premultiplied alpha colorspace.

I'm afraid the problem is more complex than I anticipated. An ideal solution would probably require using non-negative filter in all transparent areas and transitioning to sharpening filter in fully-opaque areas. But I'm not sure if that's worth pursuing. For my needs I'm going to stick to bilinear for whole RGBA images for now.
